### ISSUE TITLE
Error Response Possibly Lost In Batch and Statement

### ISSUE THREAD

**Issue by nebhale** [r2dbc/r2dbc-postgresql#16]
Feels like [this](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/test/java/io/r2dbc/postgresql/PostgresqlBatchTest.java#L115) should verify an error.

**Comment by uaihebert** [comment]
I was looking at this problem. and I noticed this:
```java
        new PostgresqlBatch(client, MockCodecs.empty())
            .add("test-query")
            .execute()
            .flatMap(result -> result.map((row, rowMetadata) -> row)) //added this line
            .as(StepVerifier::create)
            // .expectNextCount(1) removed this line
            .verifyError(); // updated this line
```

If I add the flapMap transform action, than we have the expected error. I think that by not invoking the `flatMap` the response was not being triggered and the error not being emitted.

Is this assumption correct? 

I will submit the code so that you guys can take a look.

**Comment by mp911de** [comment]
Not consuming the result feels like fire and forget. I argue that errors should be propagated if the result is consumed (i.e. using `flatMap(…)` in this example).

**Comment by uaihebert** [comment]
Got it.

I will leave the PR as it is. ( :
