### ISSUE TITLE
Add LogicalDecoding

### ISSUE THREAD

**Issue by davecramer** [r2dbc/r2dbc-postgresql#18]
PostgreSQL has a feature which enables streaming changes to the client
Add functionality for this

**Comment by mp911de** [comment]
Using R2DBC Postgres for a replication connection is possible by setting the `replication` option to `database`. We can also consume a replication stream (`CopyData`) if it's started through `START_REPLICATION SLOT demo_logical_slot LOGICAL 0/0 ("skip-empty-xacts" 'true', "include-xids" 'false')`.

Using a replication connection seems to impose restrictions on what commands a connection can issue.

Consuming a replication stream seems to require a standby-update that is sent upon an agreed frequency. Probably we should introduce a similar fluent API to configure and start replication streams as in PGJDBC. The returned `ReplicationStream` should allow `mapping` of the incoming payload and we should ideally design a model that holds the payload including the LSNs so the replication message reflects what we've received from the server as this pattern lines up nicely with message-oriented consumption instead of calling getters on `ReplicationStream` to obtain LSNs.

We also require a `Mono<Void> close()` or `cancel()` method to terminate the stream. We could also leverage cancellation signals to terminate the replication stream.

See for further details: https://www.postgresql.org/docs/current/protocol-replication.html

**Comment by davecramer** [comment]
Dave Cramer


On Mon, 23 Sep 2019 at 02:43, Mark Paluch <notifications@github.com> wrote:

> Using R2DBC Postgres for a replication connection is possible by setting
> the replication option to database. We can also consume a replication
> stream (CopyData) if it's started through START_REPLICATION SLOT
> demo_logical_slot LOGICAL 0/0 ("skip-empty-xacts" 'true', "include-xids"
> 'false').
>
> Using a replication connection seems to impose restrictions on what
> commands a connection can issue.
>
Yes, it does, but you would only use a replication connection for
replication.

> Consuming a replication stream seems to require a standby-update that is
> sent upon an agreed frequency. Probably we should introduce a similar
> fluent API to configure and start replication streams as in PGJDBC. The
> returned ReplicationStream should allow mapping of the incoming payload
> and we should ideally design a model that holds the payload including the
> LSNs so the replication message reflects what we've received from the
> server as this pattern lines up nicely with message-oriented consumption
> instead of calling getters on ReplicationStream to obtain LSNs.
>
> Yes, we do need to periodically send back information to the server

> We also require a Mono<Void> close() or cancel() method to terminate the
> stream. We could also leverage cancellation signals to terminate the
> replication stream.
>
> See for further details:
> https://www.postgresql.org/docs/current/protocol-replication.html
>

+1 for this
