### ISSUE TITLE
Row.get(…, Object.class) fails with java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-postgresql#8]
Calling `Row.get(…)` with `Object.class` fails with `IllegalArgumentException`

```
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
		at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:85)
		at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:82)
```

Code to reproduce:

**SQL**

```sql
CREATE TABLE IF NOT EXISTS legoset (
    id          integer CONSTRAINT id PRIMARY KEY,
    name        varchar(255) NOT NULL,
    manual      integer NULL
);

INSERT INTO legoset (id, name, manual) VALUES(42055, 'SCHAUFELRADBAGGER', 12);
```

**Java**

```java
Mono.from(connectionFactory.create()).map(c -> c.createStatement("SELECT manual FROM legoset"))
		.flatMapMany(Statement::execute)
		.flatMap(it -> it.map((r, md) -> r.get("manual", Object.class)))
		.as(StepVerifier::create)
		.expectNextCount(1)
		.verifyComplete();
```

**Comment by nebhale** [comment]
@mp911de [Sigh](https://twitter.com/jroper/status/1022337463212072960).

**Comment by crivera** [comment]
Hi

i just downloaded the example from https://github.com/hantsy/spring-reactive-sample/tree/master/data-r2dbc and tried to run it but get the same error.

`
ERROR reactor.Flux.OnErrorResume.2 -
org.springframework.data.mapping.MappingException: Could not read property @org.springframework.data.relational.core.mapping.Column(value="title", keyColumn="")private java.lang.String com.example.demo.Post.title from result set!
	at org.springframework.data.r2dbc.function.convert.EntityRowMapper.readFrom(EntityRowMapper.java:101)
...
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:91)

`

And its using 1.0.0.M5

Any help would be great!
